const APP_NAME = "simple-scratch";
const DEFAULT_SCRATCH_FOLDER_NAME = "scratch";
const DEFAULT_SCRATCH_FILE_NAME = "scratch";

const GLOBAL_SCRATCH_ENABLED = false;
const GLOBAL_DEFAULT_SCRATCH_FOLDER_NAME = "scratch";
const GLOBAL_DEFAULT_SCRATCH_FILE_NAME = "scratch";

const VALID_FILENAME_REGEX = "^[a-zA-Z]{1}[a-zA-Z\\d\\-\\_]+$";

module.exports = {
  APP_NAME,
  DEFAULT_SCRATCH_FOLDER_NAME,
  DEFAULT_SCRATCH_FILE_NAME,
  GLOBAL_SCRATCH_ENABLED,
  GLOBAL_DEFAULT_SCRATCH_FOLDER_NAME,
  GLOBAL_DEFAULT_SCRATCH_FILE_NAME,
  VALID_FILENAME_REGEX
};
